import type { CityId, Driver, OrderDraft } from '../types'
import { etaFromMeters, haversineMeters } from './geo'
import { getCity } from './cities'

export const CITY_CENTER: [number, number] = getCity('caracas').center

export const PLACES: Record<string, [number, number]> = getCity('caracas').places

export const EMPTY_ORDER: OrderDraft = {
  origin: '',
  destination: '',
  originCoords: null,
  destCoords: null,
  originHint: '',
  destHint: '',
  clientName: '',
  clientPhone: '',
  paymentMethod: '',
  amount: '',
  notes: '',
  serviceTypeId: '',
}

export const SAMPLE_WHATSAPP = `Hola, necesito un motorizado urgente
De: Av. Francisco de Miranda, Altamira
Hasta: CC Sambil, Chacao
Cliente: María González
Tel: 0412-555-0189
Pago: Efectivo $15`

type SeedDriver = Omit<Driver, 'distanceM' | 'etaMin'>

const BASE_DRIVERS: SeedDriver[] = [
  {
    id: 'drv-01',
    name: 'Juan Pérez',
    phone: '584145550123',
    vehicle: 'Moto Empire 150',
    licensePlate: 'AB123CD',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-66.8508, 10.4996],
    battery: 86,
    zone: 'Altamira',
    notes: 'Turno mañana · cubre Chacao',
    cityId: 'caracas',
  },
  {
    id: 'drv-02',
    name: 'Ana Rojas',
    phone: '584125550234',
    vehicle: 'Moto Bera Social 150',
    licensePlate: 'XY456EF',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-66.8572, 10.4941],
    battery: 72,
    zone: 'Chacao',
    notes: '',
    cityId: 'caracas',
  },
  {
    id: 'drv-03',
    name: 'Luis Herrera',
    phone: '584165550345',
    vehicle: 'Moto Yamaha FZ 2.0',
    licensePlate: 'GH789JK',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-66.8479, 10.4928],
    battery: 94,
    zone: 'Chacao',
    notes: 'Prefiere pedidos de centro comercial',
    cityId: 'caracas',
  },
  {
    id: 'drv-04',
    name: 'Carla Méndez',
    phone: '584245550456',
    vehicle: 'Moto Honda CB 125',
    licensePlate: 'LM234NP',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-66.8614, 10.5012],
    battery: 61,
    zone: 'La Castellana',
    notes: '',
    cityId: 'caracas',
  },
  {
    id: 'drv-05',
    name: 'Pedro Silva',
    phone: '584145550567',
    vehicle: 'Moto Suzuki GN 125',
    licensePlate: 'QR567ST',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-66.8446, 10.5054],
    battery: 48,
    zone: 'Los Palos Grandes',
    notes: '',
    cityId: 'caracas',
  },
  {
    id: 'drv-06',
    name: 'Sofía Rivas',
    phone: '584125550678',
    vehicle: 'Moto Keeway Superlight',
    licensePlate: 'UV890WX',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-66.8691, 10.4896],
    battery: 91,
    zone: 'El Rosal',
    notes: '',
    cityId: 'caracas',
  },
  {
    id: 'drv-07',
    name: 'Miguel Torres',
    phone: '584165550789',
    vehicle: 'Moto Empire Arsen 2',
    licensePlate: 'YZ345AB',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-66.8398, 10.4872],
    battery: 77,
    zone: 'Las Mercedes',
    notes: '',
    cityId: 'caracas',
  },
  {
    id: 'drv-08',
    name: 'Elena Castro',
    phone: '584245550890',
    vehicle: 'Moto TVS Apache 160',
    licensePlate: 'CD678EF',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-66.8588, 10.5088],
    battery: 55,
    zone: 'La Castellana',
    notes: '',
    cityId: 'caracas',
  },
  {
    id: 'drv-09',
    name: 'Diego Navarro',
    phone: '584145550901',
    vehicle: 'Moto Bajaj Pulsar 150',
    licensePlate: 'GH901JK',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'busy',
    coords: [-66.8724, 10.4964],
    battery: 33,
    zone: 'Plaza Venezuela',
    notes: 'En servicio hasta las 18:00',
    cityId: 'caracas',
  },
  {
    id: 'drv-10',
    name: 'Valeria Díaz',
    phone: '584125550012',
    vehicle: 'Moto Honda Wave 110',
    licensePlate: 'LM012NP',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'busy',
    coords: [-66.8412, 10.4988],
    battery: 41,
    zone: 'Altamira',
    notes: '',
    cityId: 'caracas',
  },
  {
    id: 'drv-sci-01',
    name: 'Héctor Ramírez',
    phone: '584145551101',
    vehicle: 'Moto Empire Arsen 2',
    licensePlate: 'TA101AB',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-72.2242, 7.7678],
    battery: 88,
    zone: 'Centro',
    notes: 'Cubre 5 de Julio y la 7ma',
    cityId: 'san_cristobal',
  },
  {
    id: 'drv-sci-02',
    name: 'Yelitza Mora',
    phone: '584245551212',
    vehicle: 'Moto Bera Social 150',
    licensePlate: 'TA202CD',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-72.2094, 7.7806],
    battery: 74,
    zone: 'La Concordia',
    notes: '',
    cityId: 'san_cristobal',
  },
  {
    id: 'drv-sci-03',
    name: 'Andrés Contreras',
    phone: '584165551323',
    vehicle: 'Moto Yamaha FZ 2.0',
    licensePlate: 'TA303EF',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-72.1992, 7.7704],
    battery: 91,
    zone: 'Pueblo Nuevo',
    notes: 'Turno tarde',
    cityId: 'san_cristobal',
  },
  {
    id: 'drv-sci-04',
    name: 'Karina Chacón',
    phone: '584125551434',
    vehicle: 'Moto Honda Wave 110',
    licensePlate: 'TA404GH',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-72.2296, 7.7608],
    battery: 63,
    zone: 'Baratillo',
    notes: '',
    cityId: 'san_cristobal',
  },
  {
    id: 'drv-sci-05',
    name: 'José Zambrano',
    phone: '584145551545',
    vehicle: 'Moto Suzuki GN 125',
    licensePlate: 'TA505JK',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'busy',
    coords: [-72.2044, 7.7856],
    battery: 42,
    zone: 'La Erminia',
    notes: 'En servicio hasta las 17:00',
    cityId: 'san_cristobal',
  },
  {
    id: 'drv-sci-06',
    name: 'María Peña',
    phone: '584245551656',
    vehicle: 'Moto Keeway Superlight',
    licensePlate: 'TA606LM',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-72.2268, 7.7662],
    battery: 81,
    zone: 'Centro',
    notes: '',
    cityId: 'san_cristobal',
  },
  {
    id: 'drv-cuc-01',
    name: 'Camilo García',
    phone: '573155551101',
    vehicle: 'Moto AKT NKD 125',
    licensePlate: 'CUC11A',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-72.5062, 7.8946],
    battery: 84,
    zone: 'Centro',
    notes: '',
    cityId: 'cucuta',
  },
  {
    id: 'drv-cuc-02',
    name: 'Laura Vargas',
    phone: '573105551212',
    vehicle: 'Moto Yamaha NMAX',
    licensePlate: 'CUC22B',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-72.4894, 7.9104],
    battery: 71,
    zone: 'Caobos',
    notes: 'Prefiere zona comercial',
    cityId: 'cucuta',
  },
  {
    id: 'drv-cuc-03',
    name: 'Diego Quintero',
    phone: '573165551323',
    vehicle: 'Moto Honda CB 125',
    licensePlate: 'CUC33C',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-72.4796, 7.8852],
    battery: 93,
    zone: 'Prados',
    notes: '',
    cityId: 'cucuta',
  },
  {
    id: 'drv-cuc-04',
    name: 'Natalia Niño',
    phone: '573145551434',
    vehicle: 'Moto Bajaj Pulsar 150',
    licensePlate: 'CUC44D',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'busy',
    coords: [-72.5104, 7.9272],
    battery: 38,
    zone: 'Aeropuerto',
    notes: 'Recogida en Camilo Daza',
    cityId: 'cucuta',
  },
  {
    id: 'drv-cuc-05',
    name: 'Sergio Sandoval',
    phone: '573125551545',
    vehicle: 'Moto Suzuki GN 125',
    licensePlate: 'CUC55E',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-72.5192, 7.8806],
    battery: 67,
    zone: 'San Luis',
    notes: '',
    cityId: 'cucuta',
  },
  {
    id: 'drv-bog-01',
    name: 'Felipe Rojas',
    phone: '573105552101',
    vehicle: 'Moto Yamaha NMAX',
    licensePlate: 'BOG11A',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-74.0624, 4.6486],
    battery: 90,
    zone: 'Chapinero',
    notes: '',
    cityId: 'bogota',
  },
  {
    id: 'drv-bog-02',
    name: 'Camila Restrepo',
    phone: '573155552212',
    vehicle: 'Moto Honda PCX',
    licensePlate: 'BOG22B',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-74.0306, 4.6954],
    battery: 76,
    zone: 'Usaquén',
    notes: 'Turno mañana',
    cityId: 'bogota',
  },
  {
    id: 'drv-bog-03',
    name: 'Andrés Cárdenas',
    phone: '573165552323',
    vehicle: 'Moto AKT NKD 125',
    licensePlate: 'BOG33C',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-74.0744, 4.5982],
    battery: 58,
    zone: 'Centro',
    notes: '',
    cityId: 'bogota',
  },
  {
    id: 'drv-bog-04',
    name: 'Valentina Gómez',
    phone: '573145552434',
    vehicle: 'Moto Bajaj Pulsar NS',
    licensePlate: 'BOG44D',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'available',
    coords: [-74.0536, 4.6674],
    battery: 82,
    zone: 'Zona T',
    notes: 'Cubre Parque 93',
    cityId: 'bogota',
  },
  {
    id: 'drv-bog-05',
    name: 'Julián Mejía',
    phone: '573125552545',
    vehicle: 'Moto Suzuki Gixxer',
    licensePlate: 'BOG55E',
    driverPhoto: '',
    vehiclePhoto: '',
    status: 'busy',
    coords: [-74.0484, 4.6762],
    battery: 44,
    zone: 'Parque 93',
    notes: 'En servicio hasta las 19:00',
    cityId: 'bogota',
  },
]

function withMetrics(driver: SeedDriver): Driver {
  return {
    ...driver,
    distanceM: 0,
    etaMin: 0,
  }
}

export function getFleet(): Driver[] {
  return BASE_DRIVERS.map(withMetrics)
}

export function seedMissingCityDrivers(existing: Driver[]): Driver[] {
  const present = new Set(existing.map((driver) => driver.cityId))
  const missing: CityId[] = []
  for (const driver of BASE_DRIVERS) {
    if (!present.has(driver.cityId) && !missing.includes(driver.cityId)) {
      missing.push(driver.cityId)
    }
  }
  if (missing.length === 0) return existing
  return [
    ...existing,
    ...BASE_DRIVERS.filter((driver) => missing.includes(driver.cityId)).map(withMetrics),
  ]
}

export const NEARBY_RADIUS_M = 1500

export function rankCandidates(
  drivers: Driver[],
  origin: [number, number],
  limit = 5,
  maxDistanceM = Infinity,
): Driver[] {
  return drivers
    .filter((driver) => driver.status === 'available')
    .map((driver) => {
      const distanceM = Math.round(haversineMeters(driver.coords, origin))
      return {
        ...driver,
        distanceM,
        etaMin: etaFromMeters(distanceM),
      }
    })
    .filter((driver) => driver.distanceM <= maxDistanceM)
    .sort((a, b) => a.distanceM - b.distanceM)
    .slice(0, limit)
}

export function resolvePlace(query: string): [number, number] | null {
  const normalized = query.toLowerCase().trim()
  if (PLACES[normalized]) return PLACES[normalized]

  const match = Object.entries(PLACES).find(([key]) => normalized.includes(key))
  return match ? match[1] : null
}

export const SCREENSHOT_ORDER: OrderDraft = {
  origin: 'Las Mercedes, Calle París',
  destination: 'Los Palos Grandes, Av. Andrés Bello',
  originCoords: PLACES['las mercedes'],
  destCoords: PLACES['los palos grandes'],
  originHint: 'Las Mercedes',
  destHint: 'Los Palos Grandes',
  clientName: 'Ricardo Blanco',
  clientPhone: '0414-622-7741',
  paymentMethod: 'Pago móvil',
  amount: '$22',
  notes: '',
  serviceTypeId: 'svc-delivery',
}
